### ISSUE TITLE
Info: How to perform test in the autoconf

### ISSUE THREAD

**Issue by ratagupt** [autotools-mirror/autoconf#1]
I have a following configure.ac script which is not working, Looking for help here.

AC_ARG_VAR(MIN_UCASE_CHRS, [minimum number of upper case characters in the password])
AS_IF([test "x$MIN_UCASE_CHRS" == "x"], [MIN_UCASE_CHRS=3])
AC_DEFINE_UNQUOTED([MIN_UCASE_CHRS], [$MIN_UCASE_CHRS], [minimum number of upper case characters in the password])

AC_ARG_VAR(MIN_LCASE_CHRS, [minimum number of lower case characters in the password])
AS_IF([test "x$MIN_LCASE_CHRS" == "x"], [MIN_LCASE_CHRS=3])
AC_DEFINE_UNQUOTED([MIN_LCASE_CHRS], [$MIN_LCASE_CHRS], [minimum number of lower case characters in the password])

AC_ARG_VAR(MIN_DIGITS, [minimum number of digits in the password])
AS_IF([test "x$MIN_DIGITS" == "x"], [MIN_DIGITS=3])
AC_DEFINE_UNQUOTED([MIN_DIGITS], [$MIN_DIGITS], [minimum number of digits in the password])

AC_ARG_VAR(MIN_PASSWORD_LENGTH, [minimum number of digits in the password])
AS_IF([test "x$MIN_PASSWORD_LENGTH" == "x"], [MIN_PASSWORD_LENGTH=8])
AC_DEFINE_UNQUOTED([MIN_PASSWORD_LENGTH], [$MIN_PASSWORD_LENGTH], [min password length])

#AS_IF([test $MIN_DIGITS + $MIN_LCASE_CHRS + $MIN_UCASE_CHRS > $MIN_PASSWORD_LENGTH], [AC_MSG_ERROR([Min password length should be greater then sum of minLcase,Min U case,Min Digits])])

**if test $MIN_DIGITS + $MIN_LCASE_CHRS + $MIN_UCASE_CHRS >  $MIN_PASSWORD_LENGTH
then
        AC_MSG_ERROR([Min password length should be greater then sum of minLcase,Min U case,Min Digits])
fi**
I was expecting that during configure step I should get an error saying "Min password length should be greater then sum of ...".
Can you help here what I am missing?

**Comment by TimothyGu** [comment]
This is not a bug tracker for autoconf, merely a mirror of its source code. Sorry.
